version: '3'
services:
  mysql:
    container_name: degustabox-mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./etc/infrastructure/database/data:/var/lib/mysql
      - ./etc/infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    container_name: degustabox-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}?serverVersion=5.7
    depends_on:
      - mysql

  nginx:
    container_name: degustabox-nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8010:81"
      - "8020:82"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php